apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: rsync-secrets
spec:
  name: rsync-secrets
  keysMap:
    rsyncd_secrets:
      path: secrets/data/pytorch/rsync
      key: rsyncd_secrets
    auth_files:
      path: secrets/data/pytorch/rsync
      key: auth_files
