resources:
  - https://github.com/opensourceways/app-repo/deploy?ref=stable
  - namespace.yaml
  - secrets.yaml
commonLabels:
  app: mindxdle-repo
patchesStrategicMerge:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
namespace: mindxdl-dailybuild


