apiVersion: v1
kind: Service
metadata:
  name: repo-service
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: 20ba5eb8-b0c8-43da-bea3-8c88f06c2a20
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  loadBalancerIP: 121.36.12.102
  externalTrafficPolicy: Cluster
  ports:
    - name: rsync-ssh-server-port
      port: 22
      targetPort: 22
      # used to be visitable via nodeport
      nodePort: 30328