---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "helm.sh/chart": "jenkins-1.7.4"
    "app.kubernetes.io/managed-by": "Tiller"
    "app.kubernetes.io/instance": "jenkins"
    "app.kubernetes.io/component": "jenkins-master"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      "app.kubernetes.io/component": "jenkins-master"
      "app.kubernetes.io/instance": "jenkins"
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": 'jenkins'
        "helm.sh/chart": "jenkins-1.7.4"
        "app.kubernetes.io/managed-by": "Tiller"
        "app.kubernetes.io/instance": "jenkins"
        "app.kubernetes.io/component": "jenkins-master"
      annotations:
        checksum/config: 7125987d703247e800c91cc5b05b6a04195a4ea8a804ac62fc2618c34108b2f0
    spec:
      imagePullSecrets:
        - name: huawei-swr-image-pull-secret
      securityContext:
        runAsUser: 0
      serviceAccountName: "jenkins"
      containers:
        - name: jenkins
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/jenkins:lts
          imagePullPolicy: "Always"
          args: [ "--argumentsRealm.passwd.$(ADMIN_USER)=$(ADMIN_PASSWORD)",  "--argumentsRealm.roles.$(ADMIN_USER)=admin"]
          env:
            - name: JAVA_OPTS
              value: ""
            - name: JENKINS_OPTS
              value: ""
            - name: JENKINS_SLAVE_AGENT_PORT
              value: "50000"
            - name: TZ
              value: Asia/Shanghai
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-password
                  name: tanggula-jenkins
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-user
                  name: tanggula-jenkins
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 50000
              name: slavelistener
          livenessProbe:
            httpGet:
              path: "/login"
              port: http
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: 12000m
              memory: 32000Mi
            requests:
              cpu: 6000m
              memory: 12000Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/jenkins_home
              name: jenkins-home
              readOnly: false
            - mountPath: /var/jenkins_config
              name: jenkins-config
              readOnly: true
            - mountPath: /usr/share/jenkins/ref/secrets/
              name: secrets-dir
              readOnly: false
            - mountPath: /usr/share/jenkins/ref/plugins/
              name: plugin-dir
              readOnly: false
      initContainers:
        - name: copy-default-config
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/jenkins:lts
          imagePullPolicy: "Always"
          command: [ "sh", "/var/jenkins_config/apply_config.sh" ]
          env:
            - name: JENKINS_UC_DOWNLOAD
              value: "https://mirrors.tuna.tsinghua.edu.cn/jenkins"
            - name: JENKINS_UC
              value: "https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json"
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-password
                  name: tanggula-jenkins
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-user
                  name: tanggula-jenkins
          resources:
            limits:
              cpu: 4000m
              memory: 4096Mi
            requests:
              cpu: 2000m
              memory: 2048Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/jenkins_home
              name: jenkins-home
            - mountPath: /var/jenkins_config
              name: jenkins-config
            - mountPath: /usr/share/jenkins/ref/secrets/
              name: secrets-dir
            - mountPath: /usr/share/jenkins/ref/plugins
              name: plugins
            - mountPath: /var/jenkins_plugins
              name: plugin-dir
      volumes:
        - name: plugins
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: jenkins-config
          configMap:
            name: jenkins
        - name: secrets-dir
          emptyDir: {}
        - name: plugin-dir
          emptyDir: {}
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: tanggula-jenkins-pvc
