resources:
  - https://github.com/opensourceways/app-jenkins/deploy-without-agent?ref=stable
  - secrets.yaml
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
commonLabels:
  app: tanggula-jenkins
commonAnnotations:
  owner: tommylikehu
  email: "tommylikehu@gmail.com"
patchesStrategicMerge:
  - remove.yaml
  - service.yaml
patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Service
      name: jenkins
    path: selector.yaml
namespace: tanggula-jenkins
