---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pytorch-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: csi-disk