# Resource for small specification slave pods
apiVersion: v1
kind: Service
metadata:
  name: x86-check-slaves-service
  labels:
    app: x86-check-slaves
spec:
  ports:
    - port: 80
      name: port-placeholder
  clusterIP: None
  selector:
    app: x86-check-slaves

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: x86-check-slaves
  labels:
    app: x86-check-slaves
spec:
  serviceName: x86-check-slaves-service
  replicas: 2
  selector:
    matchLabels:
      app: x86-check-slaves
  template:
    metadata:
      labels:
        app: x86-check-slaves
    spec:
      initContainers:
        - name: slave-init
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/jenkins-slave-tools:0.0.1
          volumeMounts:
            - mountPath: /home/jenkins/share-config
              name: jenkins-share-config
          env:
            - name: JENKINS_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_USER_NAME
              value: admin
            - name: JENKINS_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jenkins-secret
                  key: password
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://jenkins.jenkins.svc.cluster.local
            - name: JENKINS_SHARE_FOLDER
              value: /home/jenkins/share-config
            - name: EXECUTOR_NUMBERS
              value: "2"
            - name: NODE_LABELS
              value: x86 x86-check-ubuntu
          args: ["$(JENKINS_URL)", "$(JENKINS_USER_NAME)", "$(JENKINS_USER_PASSWORD)", "$(JENKINS_NODE_NAME)", "$(EXECUTOR_NUMBERS)", "$(JENKINS_AGENT_WORKDIR)", "$(NODE_LABELS)", "$(JENKINS_SHARE_FOLDER)"]
      containers:
        - name: jenkins-slave
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/pytorch/ubuntu_checkcode:v1
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: /home/jenkins/agent-working-dir
              name: check-workspace-pvc
            - mountPath: /home/jenkins/share-config
              name: jenkins-share-config
          command:
            - /bin/sh
            - -c
            - |
              export JENKINS_SECRET=`cat /home/jenkins/share-config/node_secret.id`;
              exec jenkins-agent
          resources:
            requests:
              cpu: 4000m
              memory: 4000Mi
            limits:
              cpu: 8000m
              memory: 16000Mi
          env:
            - name: JENKINS_TUNNEL
              value: jenkins-agent.jenkins.svc.cluster.local:50000
            - name: JENKINS_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://jenkins.jenkins.svc.cluster.local
      volumes:
        - name: jenkins-share-config
          emptyDir: {}
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: check-workspace-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
        storageClassName: "csi-disk"
