resources:
  - https://github.com/opensourceways/app-repo/deploy?ref=stable
  - pvc.yaml
  - namespace.yaml
  - secrets.yaml
commonLabels:
  app: ascend-dailybuild-repo
commonAnnotations:
  owner: tommylikehu
  email: "tommylikehu@gmail.com"
patchesStrategicMerge:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
namespace: ascend-dailybuild


