---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ascend-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Gi
  storageClassName: csi-disk