---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cce-evs-import-ascend-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20000Gi
  storageClassName: csi-disk
