apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: jenkins-ingress
spec:
  tls:
    - hosts:
        - ci.ascend.huawei.com
  rules:
    - host: ci.ascend.huawei.com
      http:
        paths:
          - backend:
              serviceName: jenkins
              servicePort: 80
            path: /
