apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: jenkins-ingress
spec:
  tls:
    - hosts:
        - jenkins.osinfra.cn
      secretName: jenkins-tls
  rules:
    - host: jenkins.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: jenkins
              servicePort: 80
            path: /
