---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: openeuler-jenkins
spec:
  name: openeuler-jenkins
  keysMap:
    jenkins-admin-user:
      path: secrets/data/pytorch/jenkins
      key: jenkins-admin-user
    jenkins-admin-password:
      path: secrets/data/pytorch/jenkins
      key: jenkins-admin-password
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: website-secrets
spec:
  name: website-secrets
  type: kubernetes.io/tls
  keysMap:
    ca.crt:
      path: secrets/data/pytorch/website
      key: huawei_cert
    tls.crt:
      path: secrets/data/pytorch/website
      key: huawei_cert
    tls.key:
      path: secrets/data/pytorch/website
      key: huawei_key

