---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  template:
    spec:
      imagePullSecrets:
        - name: huawei-swr-image-pull-secret
      containers:
        - name: jenkins
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/jenkins:lts
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-password
                  name: pytorch-jenkins
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-user
                  name: pytorch-jenkins
          resources:
            limits:
              cpu: 12000m
              memory: 32000Mi
            requests:
              cpu: 6000m
              memory: 12000Mi
      initContainers:
        - name: copy-default-config
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/jenkins:lts
          env:
            - name: JENKINS_UC_DOWNLOAD
              value: "https://mirrors.tuna.tsinghua.edu.cn/jenkins"
            - name: JENKINS_UC
              value: "https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json"
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-password
                  name: pytorch-jenkins
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-user
                  name: pytorch-jenkins
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: cce-evs-mindxdl-jenkins
